films/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('films',
    url(r'^$', 'views.index', name='index'),
    url(r'^films/$', 'views.films', {'id': None}, name='films_all'),
    url(r'^films/(?P<id>\d+)/$', 'views.films', name='films_id')
)

restfulwebapisite/urls.py
# -*- coding: utf-8 -*-

"""urls module of the website."""

from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'restfulwebapisite.views.home', name='home'),
    # url(r'^restfulwebapisite/', include('restfulwebapisite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^cinema/', include('cinema.urls', namespace='cinema', app_name='cinema')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts', app_name='accounts')),

    #url(r'^i18n/', include('django.conf.urls.i18n')),
)

# Copied and changed from django.conf.urls.i18n
urlpatterns += patterns('',
    url(r'^i18n/setlang/$', 'accounts.views.custom_i18n', name='set_language'),
)

restfulwebapisite/views.py
# -*- coding: utf-8 -*-

"""views module of the website."""

from django.shortcuts import render


def home(request):
    """Home page."""
    return render(request, 'home.html')

restfulwebapisite/templates/base.html
<!DOCTYPE html>

{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

{% load static from staticfiles %}
{% static "css/base.css" as base_css %}
{% static "js/httprequest.js" as httprequest_js %}

<html lang="{{ LANGUAGE_CODE }}">
    <head>
        <meta charset="UTF-8">
        <title>RESTful Web API - {% block title %}{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{{ base_css }}" />
        <script src="{{ httprequest_js }}" type='text/javascript'></script>
    </head>
    <body>
        <header id="page-header">
            <div id="logo">
                <a href="{% url 'home' %}">RESTful Web API</a>
            </div>
            <div id="motto">
                REST, HATEOAS, HTTP, API, Python, Django... 
            </div>
            <div id="login">
                {% if user.is_authenticated  %}
                    <a href="{% url 'accounts:logout' %}">{% trans "Log Out" %}</a>
                {% else %}
                    <a href="{% url 'accounts:login' %}">{% trans "Log In" %}</a>
                {% endif %}
            </div>
            <div id="language-selection">
                <form action="{% url 'set_language' %}" method="post">
                    <div>
                        {% csrf_token %}
                        <input name="next" type="hidden" value="{{ get_full_path }}" />
                        <select name="language">
                            {% get_language_info_list for LANGUAGES as langs %}
                            {% for language in langs %}
                                <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                                    {{ language.name_local }} ({{ language.code }})
                                </option>
                            {% endfor %}
                        </select>
                        {# Translators: Language selection: submit button. #}
                        <input type="submit" value="{% trans "Go" %}" />
                    </div>
                </form>
            </div>
        </header>
        <div id="content-wrapper">
            <nav>
                <ul>
                    <li>
                        <a href="{% url 'home' %}">{% trans "Home" %}</a>
                    </li>
                    <li>
                        <a href="">{% trans "Examples" %}</a>
                    </li>
                    <li>
                        <a href="">{% trans "Django app" %}</a>
                    </li>
                    <li>
                        <a href="">RESTfulWebAPI</a>
                    </li>
                </ul>
            </nav>
            <div class="separator"></div>
            <div id="content">
                {% block content %}{% endblock %}
            </div>
        </div>
        <footer id="top-footer">
            <section id="logos">
                <div id="logo-html5">
                    <a href="http://www.w3.org/html/logo/">
                        <img src="http://www.w3.org/html/logo/badge/html5-badge-h-solo.png" width="63" height="64" alt="HTML5 Powered" title="HTML5 Powered">
                    </a>
                </div>
                <div id="logo-django">
                    <a href="http://www.djangoproject.com/">
                        <img src="https://www.djangoproject.com/m/img/badges/djangopowered126x54.gif" alt="Powered by Django." title="Powered by Django." />
                    </a>
                </div>
                <div id="logo-css">
                    <a href="http://jigsaw.w3.org/css-validator/check/referer">
                        <img style="border:0;width:88px;height:31px" src="http://jigsaw.w3.org/css-validator/images/vcss" alt="Valid CSS!" />
                    </a>
                </div>
            </section>
            <section id="links">
                <h3>{% trans "Links" %}</h3>
                <ul>
                    <li><a href="http://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm">Representational State Transfer (REST)</a></li>
                    <li><a href="http://roy.gbiv.com/untangled/2008/rest-apis-must-be-hypertext-driven">REST APIs must be hypertext-driven</a></li>
                    <li><a href="http://www.w3.org/Provider/Style/URI.html">Cool URIs don't change</a></li>
                    <li><a href="http://restpatterns.org/">REST & WOA Wiki</a></li>
                    <li><a href="http://blog.steveklabnik.com/posts/2011-07-03-nobody-understands-rest-or-http">Nobody Understands REST or HTTP</a></li>
                    <li><a href="http://www.informit.com/articles/article.aspx?p=1566460">Versioning REST Services</a></li>
                </ul>
            </section>
            <section id="site-info">
                <h3>{% trans "Info" %}</h3>
                <ul>
                    <li><a href="https://github.com/juliotrigo">juliotrigo @ GitHub</a></li>
                    <li><a href="https://bitbucket.org/juliotrigo">juliotrigo @ Bitbucket</a></li>
                    <li><a href="https://twitter.com/juliotrigo">juliotrigo @ Twitter</a></li>
                    <li><a href="">{% trans "About" %} juliotrigo</a></li>
                    <li><a href="">{% trans "Contact" %}</a></li>
                    <li><a href="http://juliotrigo.wordpress.com/category/programming/">{% trans "Blog" %}</a></li>
                </ul>
            </section>
        </footer>
        <footer id="bottom-footer">
            <section id="credits">
                <ul>
                    <li><a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/deed.en_GB"><img alt="Creative Commons Licence" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/3.0/88x31.png" /></a><br />This work by <a href="http://juliotrigo.com" property="http://creativecommons.org/ns#attributionName" rel="http://creativecommons.org/ns#attributionURL">juliotrigo</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/deed.en_GB">Creative Commons Attribution-ShareAlike 3.0 Unported License</a>.</li>
                    <li><span>HTML5 Logo by <a href="http://www.w3.org/"><abbr title="World Wide Web Consortium">W3C</abbr></a></span></li>
                </ul>
            </section>
        </footer>
    </body>
</html>

restfulwebapisite/templates/home.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Home" %}{% endblock %}

{% block content %}
    {# Translators: This text will appear in all pages. #}
    <h2>{% trans "Welcome to RESTfulWebAPI.com" %}</h2>
    <p>{% trans "Please find below the services currently available:" %}</p>
    <h3><a href="{% url 'cinema:index' %}">{% trans "Cinema" %}</a></h3>
{% endblock %}